project:
  title: "report-quarto"
  type: website

website:
  title: "Relatório TP1 Algoritmos 2"
  navbar:
    left:
      - text: Home
        href: report-quarto.qmd

output-dir: docs

formats:
  html: default
